language: python

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7

# Get base LJM/Kipling setup
before_install:
  - |
    pip install -U pip
    pip install --egg --no-binary pyenv pyenv
    export PATH=~/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install --skip-existing $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
    pyenv shell $PYTHON_VERSION
    pip install -U pip setuptools wheel py
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh install-linux.sh -t; fi

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - pytest tests