language: python
python:
  # CPython versions
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - os: linux
      dist: xenial

# Get base LJM/Kipling setup
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh install-linux.sh -t; fi

# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest tests