language: python
python:
  - "3.5"
  - "3.7-dev"

# Get base LJM/Kipling setup
before_install:
  - wget https://labjack.com/sites/default/files/software/labjack_ljm_software_2018_08_30_x86_64.tar.gz
  - tar -zvxf labjack_ljm_software_2018_08_30_x86_64.tar.gz
  - sudo ./labjack_ljm_software_2018_08_30_x86_64/labjack_ljm_installer.run
  - wget https://labjack.com/sites/default/files/software/Python_LJM_2018_10_19.zip
  - unzip Python_LJM_2018_10_19.zip
  - cd Python_LJM_2018_10_19
  - pip install .
  - cd ..

# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest tests
