language: python

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5.1

    - os: linux
      dist: xenial
      language: python
      python: 3.7

    - os: linux
      dist: xenial
      language: python
      python: 3.6

    - os: linux
      dist: xenial
      language: python
      python: 3.5

# Get base LJM/Kipling setup
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip install -U pip;
      pip install --egg --no-binary pyenv pyenv;
      export PATH=~/.pyenv/bin:$PATH;
      eval "$(pyenv init -)";
      pyenv install --skip-existing $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      pyenv shell $PYTHON_VERSION;
      pip install -U pip setuptools wheel py;
      pip install pytest
      curl -O https://labjack.com/sites/default/files/software/labjack_ljm_software_2018_08_30.zip
      unzip labjack_ljm_software_2018_08_30.zip
      sudo installer -pkg labjack_ljm_software_2018_08_30/labjack_ljm_software_2018_08_30.pkg -target /
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://labjack.com/sites/default/files/software/labjack_ljm_software_2018_08_30_x86_64.tar.gz
      tar -zvxf labjack_ljm_software_2018_08_30_x86_64.tar.gz
      sudo ./labjack_ljm_software_2018_08_30_x86_64/labjack_ljm_installer.run
    fi

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest -v tests/

deploy:
  provider: pypi
  user: "nyctanthous"
  password:
    secure: "rHu5xPXm7Nu1StrfW/QDDfdc7JMpwFwd/qJV8sZAYeHsgVHD0PSCWQ1iumZL95OWjLkbErxBpZzFz0k8WaD9RAZxspa9yNec4AAo/7faZVlm7IYRikbyCo3Ha+hgHMhfYwpxCqYGp+82GzPdR/jwD3phQGjNCziUlvGm5s12i3Ueo16xZwelGxF0EWrRYYy15CDUvO1trL7jJP+biqClmtn/ZkJEVPT5zmZfo4pvTE52I7Of1CnO06ax1aBmVzSu7JFxfD7v8076rWPIr+6qTi8Y8JiPHxaqWt/tfanep1Rtilbncl2BiIW88lPLGqp+jbyYkVvC+ZSMbRpjIJJFw6GNSOgWq2Vv0JHjc6Awds8ZLcQyBzLrKKz+GzITxfFWW1O3TvBtOU8jvmBGKFvaAJ3me3rIOtqPpH/ztkpTY4b34ZL6Ks74hYwxSZba78zJYTQOap5rcL2DqUXfj8GeN6eeRwdO8q7MwJKWXRTgK3udmYxt1BZAbijHtpqTLRStEUt2gMG4Uk2sfteen+M89ywAXI4lE/nzkkMgUugSVbF7db7mNlDlrNVGK5nFOBfcbUC+UK7tMJl9bPM9Qwb5kYZ/waIW/IGnmvGLbVn99puPamks6CnWTl1/+MF9hqXsqJ4kb0fF85dRUr/3OXAgXLz01EOUNTQQ5Dzi/R9rHQQ="
