name: labjack-controller
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - babel=2.9.1
  - blas=1.0
  - bokeh=2.3.2
  - brotlipy=0.7.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - cycler=0.10.0
  - docutils=0.17.1
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - intel-openmp=2021.2.0
  - jinja2=3.0.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pillow=8.2.0
  - pip=21.1.1
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.1
  - pytz=2021.1
  - pyyaml=5.4.1
  - qt=5.9.7
  - requests=2.25.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sphinx=4.0.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - async-generator==1.10
    - attrs==21.2.0
    - bleach==3.3.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - ipython-genutils==0.2.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - labjack-ljm==1.21.0
    - labjackcontroller==0.4.2.dev2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nbsphinx==0.8.5
    - nest-asyncio==1.5.1
    - pandocfilters==1.4.3
    - pyrsistent==0.17.3
    - pywin32==300
    - pyzmq==22.1.0
    - table-logger==0.3.6
    - testpath==0.5.0
    - traitlets==5.0.5
    - typing==3.7.4.3
    - webencodings==0.5.1
